{ pkgs, config, ... }:
let
  user = config.hostOptions.user;
in
{
  # Enable managing dconf with NixOS and home-manager
  programs.dconf.enable = true;

  home-manager.users.${user} = {
    imports = [
      ./settings.nix # Settings generated by dconf2nix
    ];

    home.packages = with pkgs; [
      dconf-editor # GUI for editing dconf entries
      dconf2nix # Convert dconf files to Nix files
    ];
  };
}
