{ lib, config, ... }: {
  options.hostOptions.dconf.background = with lib; {
    path = mkOption {
      type = types.nullOr types.pathInStore;
      default = null;
      description = "The path to the background image to use";
    };

    adjustment = mkOption {
      type = types.enum [ "zoom" ];
      default = "zoom";
      description = "The adjustment to apply if the image doesn't fit the resolution";
    };
  };

  imports = [
    ./settings.nix # Settings generated by dconf2nix
  ];

  config =
    let
      cfg = config.hostOptions.dconf;
    in
    {
      dconf.settings = lib.mkIf (cfg.background.path != null) {
        "org/gnome/desktop/background" = {
          picture-options = cfg.background.adjustment;
          picture-uri = "${cfg.background.path}";
          picture-uri-dark = "${cfg.background.path}";
        };

        "org/gnome/desktop/screensaver" = {
          picture-options = cfg.background.adjustment;
          picture-uri = "${cfg.background.path}";
        };
      };
    };
}
